### ISSUE TITLE
v0.7.0 +Werror: error: "_mm_shufflehi_epi16" redefined 

### ISSUE THREAD

**Issue by mr-c** [simd-everywhere/simde#690] opened 2020-12-31 13:04 UTC
https://dev.azure.com/themartinsteinegger/mmseqs2/_build/results?buildId=813&view=logs&j=c319d949-082a-5093-2ff3-cac79c8a3f4e&t=516e54d9-0a19-564e-c1b0-dc69dabddc8f&l=184

**Comment by nemequ** [comment] 2021-01-02 19:57
Duplicate of #682

**Closed by nemequ** 2021-01-02 19:57 UTC
