### ISSUE TITLE
Build problem for run-tests

### ISSUE THREAD

**Issue by rosbif** [simd-everywhere/simde#482] opened 2020-07-10 15:41 UTC
In run-tests, if the file xxx.h included by xxx.c is modified, make only rebuilds the C version not the C++ version.
Edit: Even `touch xxx.c` doesn't cause a C++ rebuild.

**Comment by nemequ** [comment] 2020-07-10 18:54
Use Meson.

I'd be willing to accept a patch if you can figure out how to fix this (the cmake channel on freenode could be useful if you need help), but I'm not going to spend any time working on it.  As far as I'm concerned CMake is only there for configurations I haven't managed to get working in Meson yet.

**Comment by rosbif** [comment] 2020-07-10 21:02
I think that this is a recent regression because I am sure that I would have noticed if it exhibited this behaviour previously.
Can you reproduce it or is there something wrong with my machine?
If so whatever caused the regression should be reverted.

**Comment by nemequ** [comment] 2020-07-11 06:11
> I think that this is a recent regression because I am sure that I would have noticed if it exhibited this behaviour previously.

It could be…  Most of [the recent changes](https://github.com/simd-everywhere/simde/commits/master/test/CMakeLists.txt) in the CMake build system have been to add new files.  The best suspect I see is 30044527fc7f8972d38e42c2985043324edf417e, but honestly I don't see how.

>  Can you reproduce it or is there something wrong with my machine?

I can't reproduce it.  I tried by building everything, then inserting thre of the most satisfying lines of code I've ever written:

```c
#if defined(__cplusplus)
  #error C++
#endif
```

Then running make again.  I tried several different headers and always ended up seeing the error.

I have seen CMake handle dependencies changing poorly in the past, though I'm not sure if I've encountered this exact issue.  Usually just creating a fresh build directory solves the issue, but it sounds like it has persisted for you across that?

>  If so whatever caused the regression should be reverted.

Possibly.  I'd like to have this work if possible, but it depends on what caused it and if the problem could be resolved in another way which preserves the improvement too.

**Comment by rosbif** [comment] 2020-07-11 07:52
I shall try again from a clean start the next time I pull from master.
However I am fairly certain that I did start cleanly this time but with a master from a day or two ago.

**Comment by rosbif** [comment] 2020-07-11 22:45
I confirm that I still have the problem after a fresh pull from master and the removal of the build subdirectory to make sure there is no remnants from a previous build.

**Comment by nemequ** [comment] 2020-07-12 14:34
It could be an issue with a specific version of CMake… maybe your distro's CMake package was upgraded recently?

**Comment by mr-c** [comment] 2020-12-28 18:05
@rosbif Let us know if this is still affecting you!

**Closed by mr-c** 2020-12-28 18:05 UTC
