### ISSUE TITLE
gcc 13.0.1 with O2 + i686 test dpbf16 failures and x86/avx512/dpbf16 errors

### ISSUE THREAD

**Issue by junaruga** [simd-everywhere/simde#988] opened 2023-02-10 14:05 UTC
Hello, I ran the tests with the simde v0.7.4-rc1 on Fedora rawhide (38)'s build environment. The i686 environment. The gcc's RPM version is 13.0.1-0.2.fc38 (`rpm -q gcc`). Here is the log! Could you take a look? Thanks!

```
+ bash -
=== 1.2. tests on gcc with O2 flag ===
+ BUILD_DIR=build/gcc-O2
+ CC='gcc -fno-strict-aliasing'
+ CXX='g++ -fno-strict-aliasing'
+ CFLAGS=-O2
+ CXXFLAGS=-O2
+ _setup
+ meson setup build/gcc-O2
The Meson build system
Version: 1.0.0
Source dir: /builddir/build/BUILD/simde-9609eb2cf687984277185813fdfe81b8b200377b
Build dir: /builddir/build/BUILD/simde-9609eb2cf687984277185813fdfe81b8b200377b/build/gcc-O2
Build type: native build
Project name: SIMDe
Project version: 0.7.4
C compiler for the host machine: gcc -fno-strict-aliasing (gcc 13.0.1 "gcc (GCC) 13.0.1 20230127 (Red Hat 13.0.1-0)")
C linker for the host machine: gcc -fno-strict-aliasing ld.bfd 2.39-9
C++ compiler for the host machine: g++ -fno-strict-aliasing (gcc 13.0.1 "g++ (GCC) 13.0.1 20230127 (Red Hat 13.0.1-0)")
C++ linker for the host machine: g++ -fno-strict-aliasing ld.bfd 2.39-9
Host machine cpu family: x86
Host machine cpu: i686
Library m found: YES
Compiler for C supports arguments -fopenmp-simd: YES 
Compiler for C++ supports arguments -fopenmp-simd: YES 
Compiler for C supports arguments -Wpsabi: YES 
Compiler for C++ supports arguments -Wpsabi: YES 
Library m found: YES
Build targets in project: 1530
NOTICE: Future-deprecated features used:
 * 0.64.0: {'copy arg in configure_file'}
Found ninja-1.11.1 at /usr/bin/ninja
+ _build
+ rm -f build.log
+ _time ninja -C build/gcc-O2 -v -j 6
+ head -4 build.log
+ /usr/bin/time -f '=> [%E]' ninja -C build/gcc-O2 -v -j 6
ninja: Entering directory `build/gcc-O2'
[1/3060] gcc -fno-strict-aliasing -Itest/common/common-c.p -Itest/common -I../../test/common -I. -I../.. -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c99 -O0 -g -O2 -fopenmp-simd -DSIMDE_CONSTRAINED_COMPILATION -DSIMDE_ENABLE_OPENMP -Wno-psabi -DSIMDE_TEST_BARE -MD -MQ test/common/common-c.p/common.c.o -MF test/common/common-c.p/common.c.o.d -o test/common/common-c.p/common.c.o -c ../../test/common/common.c
[2/3060] gcc -fno-strict-aliasing  -o test/common/common-c test/common/common-c.p/common.c.o -Wl,--as-needed -Wl,--no-undefined -O2 -Wl,--start-group -lm -Wl,--end-group
+ tail -3 build.log
[3059/3060] g++ -fno-strict-aliasing -Itest/mips/msa/subv-native-cpp.p -Itest/mips/msa -I../../test/mips/msa -I. -I../.. -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -O0 -g -O2 -fopenmp-simd -DSIMDE_CONSTRAINED_COMPILATION -DSIMDE_ENABLE_OPENMP -Wno-psabi -DSIMDE_TEST_BARE -MD -MQ test/mips/msa/subv-native-cpp.p/meson-generated_.._subv.cpp.o -MF test/mips/msa/subv-native-cpp.p/meson-generated_.._subv.cpp.o.d -o test/mips/msa/subv-native-cpp.p/meson-generated_.._subv.cpp.o -c test/mips/msa/subv.cpp
[3060/3060] g++ -fno-strict-aliasing  -o test/mips/msa/subv-native-cpp test/mips/msa/subv-native-cpp.p/meson-generated_.._subv.cpp.o -Wl,--as-needed -Wl,--no-undefined -O2 -Wl,--start-group -lm -Wl,--end-group
=> [14:20.19]
+ _test
+ _time meson test -C build/gcc-O2 -q --no-rebuild --print-errorlogs
+ /usr/bin/time -f '=> [%E]' meson test -C build/gcc-O2 -q --no-rebuild --print-errorlogs
▶  109/1530 dpbf16/mm_maskz_dpbf16_ps             FAIL          
▶  109/1530 dpbf16/mm256_mask_dpbf16_ps           FAIL          
▶  109/1530 dpbf16/mm512_mask_dpbf16_ps           FAIL          
▶  109/1530 dpbf16/mm512_maskz_dpbf16_ps          FAIL          
 109/1530 x86/avx512/dpbf16/emul/cpp              ERROR           0.10s   exit status 1
>>> MALLOC_PERTURB_=111 /builddir/build/BUILD/simde-9609eb2cf687984277185813fdfe81b8b200377b/build/gcc-O2/test/x86/avx512/dpbf16-emul-cpp
――――――――――――――――――――――――――――――――――――― ✀  ―――――――――――――――――――――――――――――――――――――
stderr:
test/x86/avx512/dpbf16.cpp:245: assertion failed: r[0] ~= simde_mm_loadu_ps(test_vec[i].r)[0] (-6336335.500000 ~= -6336335.000000)
test/x86/avx512/dpbf16.cpp:482: assertion failed: r[5] ~= simde_mm256_loadu_ps(test_vec[i].r)[5] (-6323842.000000 ~= -6323841.500000)
test/x86/avx512/dpbf16.cpp:971: assertion failed: r[8] ~= simde_mm512_loadu_ps(test_vec[i].r)[8] (-6323621.500000 ~= -6323621.000000)
test/x86/avx512/dpbf16.cpp:1159: assertion failed: r[0] ~= simde_mm512_loadu_ps(test_vec[i].r)[0] (-6324085.500000 ~= -6324086.000000)
(test program exited with status code 1)
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
Unknown TAP version. The first line MUST be `TAP version <int>`. Assuming version 12.
▶  114/1530 dpbf16/mm_maskz_dpbf16_ps             FAIL          
▶  114/1530 dpbf16/mm256_mask_dpbf16_ps           FAIL          
▶  114/1530 dpbf16/mm512_mask_dpbf16_ps           FAIL          
▶  114/1530 dpbf16/mm512_maskz_dpbf16_ps          FAIL          
 114/1530 x86/avx512/dpbf16/native/cpp            ERROR           0.11s   exit status 1
>>> MALLOC_PERTURB_=31 /builddir/build/BUILD/simde-9609eb2cf687984277185813fdfe81b8b200377b/build/gcc-O2/test/x86/avx512/dpbf16-native-cpp
――――――――――――――――――――――――――――――――――――― ✀  ―――――――――――――――――――――――――――――――――――――
stderr:
test/x86/avx512/dpbf16.cpp:245: assertion failed: r[0] ~= simde_mm_loadu_ps(test_vec[i].r)[0] (-6336335.500000 ~= -6336335.000000)
test/x86/avx512/dpbf16.cpp:482: assertion failed: r[5] ~= simde_mm256_loadu_ps(test_vec[i].r)[5] (-6323842.000000 ~= -6323841.500000)
test/x86/avx512/dpbf16.cpp:971: assertion failed: r[8] ~= simde_mm512_loadu_ps(test_vec[i].r)[8] (-6323621.500000 ~= -6323621.000000)
test/x86/avx512/dpbf16.cpp:1159: assertion failed: r[0] ~= simde_mm512_loadu_ps(test_vec[i].r)[0] (-6324085.500000 ~= -6324086.000000)
(test program exited with status code 1)
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
Unknown TAP version. The first line MUST be `TAP version <int>`. Assuming version 12.
Summary of Failures:
 109/1530 x86/avx512/dpbf16/emul/cpp              ERROR           0.10s   exit status 1
 114/1530 x86/avx512/dpbf16/native/cpp            ERROR           0.11s   exit status 1
Ok:                 1528
Expected Fail:      0   
Fail:               2   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            0   
Full log written to /builddir/build/BUILD/simde-9609eb2cf687984277185813fdfe81b8b200377b/build/gcc-O2/meson-logs/testlog.txt
Command exited with non-zero status 2
=> [0:21.67]
```

**Comment by mr-c** [comment] 2023-02-10 16:56
This is a duplicate of https://github.com/simd-everywhere/simde/issues/902 , thanks!

**Closed by mr-c** 2023-02-10 16:56 UTC
