### ISSUE TITLE
Some NEON implementations rely on AArch64 intrinsics even on arm32

### ISSUE THREAD

**Issue by Baggypants** [simd-everywhere/simde#71] opened 2020-01-11 19:02 UTC
Hello there. I'm trying to compile https://github.com/surge-synthesizer/surge for the Raspberry Pi 4. Surge makes a lot of use of sse2 and I'm trying to use your library. However although I consider myself to be pretty good at building and packaging software this a bit out of my headspace.

I've copied over simde-arch.h, simde-common.h, hedley.h, check.h, x86/{mmx.h,sse2.h, sse.h} and included them in the .h in place of xmmintrin.h &  immintrin.h

```
#include "simde-arch.h"
#include "simde-common.h"
#include "x86/sse.h"
#include "x86/sse2.h"
#include "x86/mmx.h"
```

when I try and build I get a whole bunch of 
```
src/common/x86/mmx.h:839:60: error: ‘vcgezq_s16’ was not declared in this scope
src/common/x86/mmx.h:1496:37: error: ‘vneg_s64’ was not declared in this scope
src/common/x86/mmx.h:1854:15: error: ‘vzip2_s8’ was not declared in this scope
src/common/x86/mmx.h:1886:16: error: ‘vzip2_s16’ was not declared in this scope
src/common/x86/mmx.h:1914:16: error: ‘vzip2_s32’ was not declared in this scope
src/common/x86/mmx.h:1940:15: error: ‘vzip1_s8’ was not declared in this scope
src/common/x86/mmx.h:1972:16: error: ‘vzip1_s16’ was not declared in this scope
src/common/x86/mmx.h:2000:16: error: ‘vzip1_s32’ was not declared in this scope
```
Which I thought were supposed to be provided by `arm_nova.h`
 and then a heap of
```
src/common/vt_dsp/shared.h:11:7: error: ‘__m128’ does not name a type; did you mean ‘__y1l’?
src/common/vt_dsp/shared.h:12:7: error: ‘__m128’ does not name a type; did you mean ‘__y1l’?
src/common/vt_dsp/shared.h:13:7: error: ‘__m128’ does not name a type; did you mean ‘__y1l’?
src/common/vt_dsp/shared.h:14:7: error: ‘__m128’ does not name a type; did you mean ‘__y1l’?
src/common/vt_dsp/shared.h:15:7: error: ‘__m128’ does not name a type; did you mean ‘__y1l’?
src/common/vt_dsp/shared.h:16:7: error: ‘__m128’ does not name a type; did you mean ‘__y1l’?
src/common/vt_dsp/shared.h:17:7: error: ‘__m128’ does not name a type; did you mean ‘__y1l’?
src/common/vt_dsp/shared.h:18:7: error: ‘__m128’ does not name a type; did you mean ‘__y1l’?
src/common/vt_dsp/shared.h:19:7: error: ‘__m128’ does not name a type; did you mean ‘__y1l’?
src/common/vt_dsp/basic_dsp.h:50:39: error: ‘_mm_load_ss’ was not declared in this scope
src/common/vt_dsp/basic_dsp.h:50:28: error: ‘_mm_max_ss’ was not declared in this scope
src/common/vt_dsp/basic_dsp.h:50:17: error: ‘_mm_min_ss’ was not declared in this scope
src/common/vt_dsp/basic_dsp.h:49:4: error: ‘_mm_store_ss’ was not declared in this scope
src/common/vt_dsp/basic_dsp.h:54:8: error: ‘__m128’ does not name a type; did you mean ‘__y1l’?
src/common/vt_dsp/basic_dsp.h:64:8: error: ‘__m128’ does not name a type; did you mean ‘__y1l’?
src/common/vt_dsp/basic_dsp.h:72:8: error: ‘__m128’ does not name a type; did you mean ‘__y1l’?
src/common/vt_dsp/basic_dsp.h:81:32: error: ‘_mm_load_ss’ was not declared in this scope
src/common/vt_dsp/basic_dsp.h:81:21: error: ‘_mm_rcp_ss’ was not declared in this scope
src/common/vt_dsp/basic_dsp.h:81:4: error: ‘_mm_store_ss’ was not declared in this scope
```

And there's more where that came from! I'm hoping I've just done the includes incompetently.

**Comment by nemequ** [comment] 2020-01-11 19:37
Interesting.  Yes, the `v*` functions should be provided by `arm_neon.h`, which should be included whenever those functions are to be used.

I'm not sure what would cause this behavior, but I'd very much like to figure it out.  Since it's an open source project, would it be possible to show me what you've done?  Maybe you could publish it to a fork?

The only thing that jumps out at me is that you really only need to include x86/sse2.h; it will pull in the other headers automatically.  That said, including them one by one shouldn't cause any problems.

If you're doing something wrong I probably need to improve the documentation.  If not, then there is a bug in SIMDe which I'd very much like to fix :)

**Comment by Baggypants** [comment] 2020-01-11 23:04
OK, I've tried just including the sse2.h and I get exactly the same issue.

The repo is here: https://gitlab.com/Baggypants/surge
Ready yourself in for a fairly involved build process. I had to build Premake5 from source on the pi https://github.com/premake/premake-core/wiki/Building-Premake it didn't seem to bad.

the surge build requirements were 
`apt install libcairo-dev libxkbcommon-x11-dev libxkbcommon-dev libxcb-cursor-dev libxcb-keysyms1-dev libxcb-util0-dev`

Once surge and all it's submodules are cloned I run the build.

To build I'm running `./build-linux.sh build --project=lv2` because the lv2 is all I'm interested in on the pi, and it will fail on the first run as it tries to compile with `-m64 -msse2` but I do a search and replace on those in the file `surge-lv2.make` that somehow gets generated at the start by premake5. 

For completion's sake I have two copies of arm_neon.h at
```
/usr/lib/gcc/arm-linux-gnueabihf/8/include/arm_neon.h
/usr/share/castxml/clang/include/arm_neon.h
```
I am running Debian 10, Buster

**Comment by nemequ** [comment] 2020-01-15 05:12
The good news is it doesn't look like you were doing anything wrong, it's a bug in SIMDe.

It looks like some of the NEON implementations require NEON on A64, but were marked as only requiring NEON.  I've disabled the ones from MMX that you have listed above, but there may still be some others, especially is SSE.

If it would be possible for you to try to compile with e1bd4e5ff60bc8c54d88395921bd62795616ba4e or later and provide a list of the functions in SIMDe which fail to compile (the messages from the SIMDe files about functions not being declared in that scope) I can disable those as well.

I'm going to try to figure out a way to test ARM32 so I can generate that list myself, and hopefully get something going in CI so this doesn't happen again.  Once that's done I'll try write some ARM32 implementations for those functions.  Until the SIMDe will just have to fall back on the portable implementations and hope the autovectorizer does a good job… it's usually surprisingly good, but not as fast as hand-written versions.  And, of course, that's only for the relatively few functions which relied on A64.

As for the second set of error messages, that appears to just be code that hasn't been ported to SIMDe.  There is [a bit of information in the README](https://github.com/nemequ/simde#usage) about this, but basically you have two choices:

The easy option is to just define `SIMDE_ENABLE_NATIVE_ALIASES` before including SIMDe (you can do this by passing `-DSIMDE_ENABLE_NATIVE_ALIASES` to the compiler, or by putting a `#define SIMDE_ENABLE_NATIVE_ALIASES` before inculding SIMDe.

Unfortunately the easy option is also a bit fragile (there is some explanation of why in in the README).  If it doesn't work, you'll need to add a `simde_` prefix everywhere.  For example, something like this should clear up the errors you mentioned above:

```diff
diff --git a/src/common/vt_dsp/basic_dsp.h b/src/common/vt_dsp/basic_dsp.h
index 267ae2e..8d8b8a5 100644
--- a/src/common/vt_dsp/basic_dsp.h
+++ b/src/common/vt_dsp/basic_dsp.h
@@ -46,147 +46,147 @@ int sine(int x);
 inline float limit_range(float x, float low, float high)
 {
    float result;
-   _mm_store_ss(&result,
-                _mm_min_ss(_mm_max_ss(_mm_load_ss(&x), _mm_load_ss(&low)), _mm_load_ss(&high)));
+   simde_mm_store_ss(&result,
+                simde_mm_min_ss(simde_mm_max_ss(simde_mm_load_ss(&x), simde_mm_load_ss(&low)), simde_mm_load_ss(&high)));
    return result;
 }
 
-inline __m128 sum_ps_to_ss(__m128 x)
+inline simde__m128 sum_ps_to_ss(simde__m128 x)
 {
-   /*__m128 a = _mm_add_ss(x,_mm_shuffle_ps(x,x,_MM_SHUFFLE(0,0,0,1)));
-   __m128 b =
-   _mm_add_ss(_mm_shuffle_ps(x,x,_MM_SHUFFLE(0,0,0,2)),_mm_shuffle_ps(x,x,_MM_SHUFFLE(0,0,0,3)));
-   return _mm_add_ss(a,b);*/
-   __m128 a = _mm_add_ps(x, _mm_movehl_ps(x, x));
-   return _mm_add_ss(a, _mm_shuffle_ps(a, a, _MM_SHUFFLE(0, 0, 0, 1)));
+   /*simde__m128 a = simde_mm_add_ss(x,simde_mm_shuffle_ps(x,x,SIMDE_MM_SHUFFLE(0,0,0,1)));
+   simde__m128 b =
+   simde_mm_add_ss(simde_mm_shuffle_ps(x,x,SIMDE_MM_SHUFFLE(0,0,0,2)),simde_mm_shuffle_ps(x,x,SIMDE_MM_SHUFFLE(0,0,0,3)));
+   return simde_mm_add_ss(a,b);*/
+   simde__m128 a = simde_mm_add_ps(x, simde_mm_movehl_ps(x, x));
+   return simde_mm_add_ss(a, simde_mm_shuffle_ps(a, a, SIMDE_MM_SHUFFLE(0, 0, 0, 1)));
 }
 
-inline __m128 max_ps_to_ss(__m128 x)
+inline simde__m128 max_ps_to_ss(simde__m128 x)
 {
-   __m128 a = _mm_max_ss(x, _mm_shuffle_ps(x, x, _MM_SHUFFLE(0, 0, 0, 1)));
-   __m128 b = _mm_max_ss(_mm_shuffle_ps(x, x, _MM_SHUFFLE(0, 0, 0, 2)),
-                         _mm_shuffle_ps(x, x, _MM_SHUFFLE(0, 0, 0, 3)));
-   return _mm_max_ss(a, b);
+   simde__m128 a = simde_mm_max_ss(x, simde_mm_shuffle_ps(x, x, SIMDE_MM_SHUFFLE(0, 0, 0, 1)));
+   simde__m128 b = simde_mm_max_ss(simde_mm_shuffle_ps(x, x, SIMDE_MM_SHUFFLE(0, 0, 0, 2)),
+                         simde_mm_shuffle_ps(x, x, SIMDE_MM_SHUFFLE(0, 0, 0, 3)));
+   return simde_mm_max_ss(a, b);
 }
 
-inline __m128 hardclip_ss(__m128 x)
+inline simde__m128 hardclip_ss(simde__m128 x)
 {
-   const __m128 x_min = _mm_set_ss(-1.0f);
-   const __m128 x_max = _mm_set_ss(1.0f);
-   return _mm_max_ss(_mm_min_ss(x, x_max), x_min);
+   const simde__m128 x_min = simde_mm_set_ss(-1.0f);
+   const simde__m128 x_max = simde_mm_set_ss(1.0f);
+   return simde_mm_max_ss(simde_mm_min_ss(x, x_max), x_min);
 }
 
 inline float rcp(float x)
 {
-   _mm_store_ss(&x, _mm_rcp_ss(_mm_load_ss(&x)));
+   simde_mm_store_ss(&x, simde_mm_rcp_ss(simde_mm_load_ss(&x)));
    return x;
 }
 
-inline __m128d hardclip8_sd(__m128d x)
+inline simde__m128d hardclip8_sd(simde__m128d x)
 {
-   const __m128d x_min = _mm_set_sd(-7.0f);
-   const __m128d x_max = _mm_set_sd(8.0f);
-   return _mm_max_sd(_mm_min_sd(x, x_max), x_min);
+   const simde__m128d x_min = simde_mm_set_sd(-7.0f);
+   const simde__m128d x_max = simde_mm_set_sd(8.0f);
+   return simde_mm_max_sd(simde_mm_min_sd(x, x_max), x_min);
 }
 
-inline __m128 hardclip_ps(__m128 x)
+inline simde__m128 hardclip_ps(simde__m128 x)
 {
-   const __m128 x_min = _mm_set1_ps(-1.0f);
-   const __m128 x_max = _mm_set1_ps(1.0f);
-   return _mm_max_ps(_mm_min_ps(x, x_max), x_min);
+   const simde__m128 x_min = simde_mm_set1_ps(-1.0f);
+   const simde__m128 x_max = simde_mm_set1_ps(1.0f);
+   return simde_mm_max_ps(simde_mm_min_ps(x, x_max), x_min);
 }
 
 inline float saturate(float f)
 {
-   __m128 x = _mm_load_ss(&f);
-   const __m128 x_min = _mm_set_ss(-1.0f);
-   const __m128 x_max = _mm_set_ss(1.0f);
-   x = _mm_max_ss(_mm_min_ss(x, x_max), x_min);
-   _mm_store_ss(&f, x);
+   simde__m128 x = simde_mm_load_ss(&f);
+   const simde__m128 x_min = simde_mm_set_ss(-1.0f);
+   const simde__m128 x_max = simde_mm_set_ss(1.0f);
+   x = simde_mm_max_ss(simde_mm_min_ss(x, x_max), x_min);
+   simde_mm_store_ss(&f, x);
    return f;
 }
 
-inline __m128 softclip_ss(__m128 in)
+inline simde__m128 softclip_ss(simde__m128 in)
 {
    // y = x - (4/27)*x^3,  x € [-1.5 .. 1.5]
-   const __m128 a = _mm_set_ss(-4.f / 27.f);
+   const simde__m128 a = simde_mm_set_ss(-4.f / 27.f);
 
-   const __m128 x_min = _mm_set_ss(-1.5f);
-   const __m128 x_max = _mm_set_ss(1.5f);
+   const simde__m128 x_min = simde_mm_set_ss(-1.5f);
+   const simde__m128 x_max = simde_mm_set_ss(1.5f);
 
-   __m128 x = _mm_max_ss(_mm_min_ss(in, x_max), x_min);
-   __m128 xx = _mm_mul_ss(x, x);
-   __m128 t = _mm_mul_ss(x, a);
-   t = _mm_mul_ss(t, xx);
-   t = _mm_add_ss(t, x);
+   simde__m128 x = simde_mm_max_ss(simde_mm_min_ss(in, x_max), x_min);
+   simde__m128 xx = simde_mm_mul_ss(x, x);
+   simde__m128 t = simde_mm_mul_ss(x, a);
+   t = simde_mm_mul_ss(t, xx);
+   t = simde_mm_add_ss(t, x);
 
    return t;
 }
 
-inline __m128 softclip_ps(__m128 in)
+inline simde__m128 softclip_ps(simde__m128 in)
 {
    // y = x - (4/27)*x^3,  x € [-1.5 .. 1.5]
-   const __m128 a = _mm_set1_ps(-4.f / 27.f);
+   const simde__m128 a = simde_mm_set1_ps(-4.f / 27.f);
 
-   const __m128 x_min = _mm_set1_ps(-1.5f);
-   const __m128 x_max = _mm_set1_ps(1.5f);
+   const simde__m128 x_min = simde_mm_set1_ps(-1.5f);
+   const simde__m128 x_max = simde_mm_set1_ps(1.5f);
 
-   __m128 x = _mm_max_ps(_mm_min_ps(in, x_max), x_min);
-   __m128 xx = _mm_mul_ps(x, x);
-   __m128 t = _mm_mul_ps(x, a);
-   t = _mm_mul_ps(t, xx);
-   t = _mm_add_ps(t, x);
+   simde__m128 x = simde_mm_max_ps(simde_mm_min_ps(in, x_max), x_min);
+   simde__m128 xx = simde_mm_mul_ps(x, x);
+   simde__m128 t = simde_mm_mul_ps(x, a);
+   t = simde_mm_mul_ps(t, xx);
+   t = simde_mm_add_ps(t, x);
 
    return t;
 }
 
-inline __m128 tanh7_ps(__m128 x)
+inline simde__m128 tanh7_ps(simde__m128 x)
 {
-   const __m128 a = _mm_set1_ps(-1.f / 3.f);
-   const __m128 b = _mm_set1_ps(2.f / 15.f);
-   const __m128 c = _mm_set1_ps(-17.f / 315.f);
-   const __m128 one = _mm_set1_ps(1.f);
-   __m128 xx = _mm_mul_ps(x, x);
-   __m128 y = _mm_add_ps(one, _mm_mul_ps(a, xx));
-   __m128 x4 = _mm_mul_ps(xx, xx);
-   y = _mm_add_ps(y, _mm_mul_ps(b, x4));
-   x4 = _mm_mul_ps(x4, xx);
-   y = _mm_add_ps(y, _mm_mul_ps(c, x4));
-   return _mm_mul_ps(y, x);
+   const simde__m128 a = simde_mm_set1_ps(-1.f / 3.f);
+   const simde__m128 b = simde_mm_set1_ps(2.f / 15.f);
+   const simde__m128 c = simde_mm_set1_ps(-17.f / 315.f);
+   const simde__m128 one = simde_mm_set1_ps(1.f);
+   simde__m128 xx = simde_mm_mul_ps(x, x);
+   simde__m128 y = simde_mm_add_ps(one, simde_mm_mul_ps(a, xx));
+   simde__m128 x4 = simde_mm_mul_ps(xx, xx);
+   y = simde_mm_add_ps(y, simde_mm_mul_ps(b, x4));
+   x4 = simde_mm_mul_ps(x4, xx);
+   y = simde_mm_add_ps(y, simde_mm_mul_ps(c, x4));
+   return simde_mm_mul_ps(y, x);
 }
 
-inline __m128 tanh7_ss(__m128 x)
+inline simde__m128 tanh7_ss(simde__m128 x)
 {
-   const __m128 a = _mm_set1_ps(-1.f / 3.f);
-   const __m128 b = _mm_set1_ps(2.f / 15.f);
-   const __m128 c = _mm_set1_ps(-17.f / 315.f);
-   const __m128 one = _mm_set1_ps(1.f);
-   __m128 xx = _mm_mul_ss(x, x);
-   __m128 y = _mm_add_ss(one, _mm_mul_ss(a, xx));
-   __m128 x4 = _mm_mul_ss(xx, xx);
-   y = _mm_add_ss(y, _mm_mul_ss(b, x4));
-   x4 = _mm_mul_ss(x4, xx);
-   y = _mm_add_ss(y, _mm_mul_ss(c, x4));
-   return _mm_mul_ss(y, x);
+   const simde__m128 a = simde_mm_set1_ps(-1.f / 3.f);
+   const simde__m128 b = simde_mm_set1_ps(2.f / 15.f);
+   const simde__m128 c = simde_mm_set1_ps(-17.f / 315.f);
+   const simde__m128 one = simde_mm_set1_ps(1.f);
+   simde__m128 xx = simde_mm_mul_ss(x, x);
+   simde__m128 y = simde_mm_add_ss(one, simde_mm_mul_ss(a, xx));
+   simde__m128 x4 = simde_mm_mul_ss(xx, xx);
+   y = simde_mm_add_ss(y, simde_mm_mul_ss(b, x4));
+   x4 = simde_mm_mul_ss(x4, xx);
+   y = simde_mm_add_ss(y, simde_mm_mul_ss(c, x4));
+   return simde_mm_mul_ss(y, x);
 }
 
-inline __m128 abs_ps(__m128 x)
+inline simde__m128 abs_ps(simde__m128 x)
 {
-   return _mm_and_ps(x, m128_mask_absval);
+   return simde_mm_and_ps(x, m128_mask_absval);
 }
 
-inline __m128 softclip8_ps(__m128 in)
+inline simde__m128 softclip8_ps(simde__m128 in)
 {
-   const __m128 a = _mm_set1_ps(-0.00028935185185f);
+   const simde__m128 a = simde_mm_set1_ps(-0.00028935185185f);
 
-   const __m128 x_min = _mm_set1_ps(-12.f);
-   const __m128 x_max = _mm_set1_ps(12.f);
+   const simde__m128 x_min = simde_mm_set1_ps(-12.f);
+   const simde__m128 x_max = simde_mm_set1_ps(12.f);
 
-   __m128 x = _mm_max_ps(_mm_min_ps(in, x_max), x_min);
-   __m128 xx = _mm_mul_ps(x, x);
-   __m128 t = _mm_mul_ps(x, a);
-   t = _mm_mul_ps(t, xx);
-   t = _mm_add_ps(t, x);
+   simde__m128 x = simde_mm_max_ps(simde_mm_min_ps(in, x_max), x_min);
+   simde__m128 xx = simde_mm_mul_ps(x, x);
+   simde__m128 t = simde_mm_mul_ps(x, a);
+   t = simde_mm_mul_ps(t, xx);
+   t = simde_mm_add_ps(t, x);
    return t;
 }
 
diff --git a/src/common/vt_dsp/shared.h b/src/common/vt_dsp/shared.h
index 33f4186..06a419c 100644
--- a/src/common/vt_dsp/shared.h
+++ b/src/common/vt_dsp/shared.h
@@ -8,12 +8,12 @@ inline float i2f_binary_cast(int i)
    return *f;
 };
 
-const __m128 m128_mask_signbit = _mm_set1_ps(i2f_binary_cast(0x80000000));
-const __m128 m128_mask_absval = _mm_set1_ps(i2f_binary_cast(0x7fffffff));
-const __m128 m128_zero = _mm_set1_ps(0.0f);
-const __m128 m128_half = _mm_set1_ps(0.5f);
-const __m128 m128_one = _mm_set1_ps(1.0f);
-const __m128 m128_two = _mm_set1_ps(2.0f);
-const __m128 m128_four = _mm_set1_ps(4.0f);
-const __m128 m128_1234 = _mm_set_ps(1.f, 2.f, 3.f, 4.f);
-const __m128 m128_0123 = _mm_set_ps(0.f, 1.f, 2.f, 3.f);
+const simde__m128 m128_mask_signbit = simde_mm_set1_ps(i2f_binary_cast(0x80000000));
+const simde__m128 m128_mask_absval = simde_mm_set1_ps(i2f_binary_cast(0x7fffffff));
+const simde__m128 m128_zero = simde_mm_set1_ps(0.0f);
+const simde__m128 m128_half = simde_mm_set1_ps(0.5f);
+const simde__m128 m128_one = simde_mm_set1_ps(1.0f);
+const simde__m128 m128_two = simde_mm_set1_ps(2.0f);
+const simde__m128 m128_four = simde_mm_set1_ps(4.0f);
+const simde__m128 m128_1234 = simde_mm_set_ps(1.f, 2.f, 3.f, 4.f);
+const simde__m128 m128_0123 = simde_mm_set_ps(0.f, 1.f, 2.f, 3.f);
```

I tnow this looks really big and complicated, but all I did was replace `_mm_` with `simde_mm_`, `_MM_` with `SIMDE_MM_`, and `__m128` with `simde__m128`.  Occasionally automating it can cause an issue, but honestly it's pretty rare and when it happen the compiler usually points you to right were the problem is.

**Comment by nemequ** [comment] 2020-01-15 16:58
I've added an arm32 build to CI (50ee51b4902807026d32aab990441370739e9e62).  I'm still working on getting it to successfully build.

**Comment by junaruga** [comment] 2020-01-15 18:00
@nemequ You did not need `libc:armhf` to run it like your i686 case?
Here is [my .travis.yml example](https://github.com/junaruga/ci-multi-arch-native-test/blob/master/.travis.yml#L29-L46) for that, with `foo:armhf`, `sudo dpkg --add-architecture armhf` and `setarch`.

**Comment by nemequ** [comment] 2020-01-15 18:24
> @nemequ You did not need `libc:armhf` to run it on arm32, like your i686 case?

I'm not sure, it's still failing in the build phase so I haven't tried running it yet.

> Here is [my .travis.yml example](https://github.com/junaruga/ci-multi-arch-native-test/blob/master/.travis.yml#L29-L46) for that, with `foo:armhf`, `sudo dpkg --add-architecture armhf` and `setarch`.

Excellent, thank you.  I have a feeling that will come in handy when I get the build part fixed.

TBH I was planning to take a look at getting the tests to run, but I figured that even if I couldn't just having it build and skipping the tests would have been useful.  Thanks to you I should be able to get the tests to actually run, too :)

**Comment by Baggypants** [comment] 2020-01-15 19:17
Certainly the changes to the simde library mean I can get further through the build. However I cannot complete the build because it looks like I've hit some assembler.

```
==== Building surge-lv2 (release_x64) ====
Running prebuild commands
python scripts/linux/emit-vector-piggy.py .
ConfigurationXml.S
src/linux/ConfigurationXml.S: Assembler messages:
src/linux/ConfigurationXml.S:8: Error: unrecognized symbol type ""
make[1]: *** [surge-lv2.make:457: obj/x64/Release/surge-lv2/ConfigurationXml.o] Error 1
make: *** [Makefile:46: surge-lv2] Error 2

** Build of lv2 failed**
src/linux/ConfigurationXml.S:8: Error: unrecognized symbol type ""
make[1]: *** [surge-lv2.make:457: obj/x64/Release/surge-lv2/ConfigurationXml.o] Error 1
make: *** [Makefile:46: surge-lv2] Error 2

** Exiting failed lv2 build**
Complete information is in build_logs/build_lv2.log
```

**Comment by Baggypants** [comment] 2020-01-15 23:04
Ok, assembler has been fixed (swap `@` with `%`)

I've now hit this. The origionl header had the include `#include <emmintrin.h>` which I believe to be still sse2 instructions. I replaced it with an include for sse2.h

```
** Build of lv2 failed**
src/common/util/FpuState.cpp:15:43: error: ‘SIMDE_MM_MASK_MASK’ was not declared in this scope
src/common/util/FpuState.cpp:15:79: error: ‘SIMDE_MM_EXCEPT_MASK’ was not declared in this scope
src/common/util/FpuState.cpp:19:55: error: ‘SIMDE_MM_MASK_MASK’ was not declared in this scope
src/common/util/FpuState.cpp:23:31: error: ‘SIMDE_MM_ROUND_NEAREST’ was not declared in this scope
src/common/util/FpuState.cpp:23:4: error: ‘SIMDE_MM_SET_ROUNDING_MODE’ was not declared in this scope
make[1]: *** [surge-lv2.make:442: obj/x64/Release/surge-lv2/FpuState.o] Error 1
make: *** [Makefile:46: surge-lv2] Error 2
```
my git repo has been updated.

**Comment by baconpaul** [comment] 2020-01-16 00:38
As I just said over on that surge issue:

I'm almost 99% sure that's ancient code we don't need. We don't even use it on the au and in the regtests. I would just comment it out, but to be safe just keep it around and put the implementation of ::set and ::restore in an "if ARM" block or some such for now (or just ifdef it out in your local copy).

**Comment by Baggypants** [comment] 2020-01-16 12:36
We have a clean compile, crash and backtrace over here: https://github.com/surge-synthesizer/surge/issues/1481#issuecomment-575127412

**Comment by nemequ** [comment] 2020-01-16 18:36
I fixed a bunch of stuff yesterday, and clang 9 now compiles and passes all our tests on arm32.  If you're willing to try compiling with clang I'd be very interested to know how it goes.

GCC 9 isn't doing quite as well yet; I'm still seeing problems, but only with AVX and later.  The GCC 7 on Ubuntu 18.04 (which is what is being used on CI) looks like it has more errors… My suspicion is that some are due to alignment issues in SIMDe, some are due to alignment issues in the tests, and some are due to compiler bugs.

I have a few ideas for dealing with the alignment issues, but Intel is a lot more forgiving about alignment issues, especially compared to older ARM architectures.  I'm going to try to work on it today.  #72 could also help here, but that's a pretty big change which is going to take some time.

As for that set of issues about missing preprocessor macros, `_MM_MASK_MASK` and `_MM_EXCEPT_MASK` weren't implemented yet.  They're not on [Intel's Intrinsics Guide](https://software.intel.com/sites/landingpage/IntrinsicsGuide/), which is where I got the list of functions to implement.  I just pushed a patch, 181f7185541f29dda72a3538aa495971d8f1983a, which defines them, but I'm not sure how useful they'll be… I don't think we can afford to check for FP errors after every operation to emulate how Intel does it, so this may just end up being a limitation of SIMDe.

For the other 3, the "correct" symbols were `simde_MM_EXCEPT_MASK`, `simde_MM_ROUND_NEAREST`, and `simde_MM_SET_ROUNDING_MODE`.  The idea was that everything would be under "simde_", but I think that was probably a bad idea… I've gone ahead and replaced them with SIMDE_* versions (66ef2e39215c54ed824bc50d9fda84dc4ac06681).

**Comment by Baggypants** [comment] 2020-01-17 10:10
The FpuState.cpp does now compile cleanly.

**Comment by Baggypants** [comment] 2020-01-22 19:03
II realise it's a bit of an ask, but would you mind looking at this debugging enabled backtrace? https://github.com/surge-synthesizer/surge/issues/1481#issuecomment-577286310

**Comment by nemequ** [comment] 2020-02-02 01:32
Sorry, I was busy with #72 and kinda forgot about this.  I don't mind helping out if I can, but could you try updating to the latest version of SIMDe first?  The latest version should eliminate a lot of bugs on the SIMDe side.

**Comment by mr-c** [comment] 2020-12-28 16:49
Hey @Baggypants , do let us know if you have any other issues. Thanks again for reporting these!

**Closed by mr-c** 2020-12-28 16:49 UTC
Labels: bug

**Comment by baconpaul** [comment] 2020-12-28 17:54
Hey it's an ancient issue and since it was written we did a full port to PI and Apple Silicon using your library. Thanks for the excellent software.

**Comment by mr-c** [comment] 2020-12-28 17:57
@baconpaul Wonderful! Can you list the project at https://github.com/simd-everywhere/simde/wiki/Projects-Using-SIMDe ?

**Comment by baconpaul** [comment] 2020-12-28 18:17
The project (Surge) is already on that list, I was happy to just find out!

**Comment by mr-c** [comment] 2020-12-28 18:20
> The project (Surge) is already on that list, I was happy to just find out!

Great! I wasn't sure if it was the same project as the original post. Did you try out the new SIMDe 0.7.0 release? Any feedback from users?
