### ISSUE TITLE
use `SIMDE_MM_SHUFFLE` within a loop: "index for __builtin_ shuffle vector must be a constant integer"

### ISSUE THREAD

**Issue by mr-c** [simd-everywhere/simde#947] opened 2022-03-19 13:51 UTC
Hi @nemequ, when I try and use `SIMDE_MM_SHUFFLE` within a loop using the index as input I get:
```
index for __builtin_ shuffle vector must be a constant integer
```
Is there a way around this?

_Originally posted by @kapsyst in https://github.com/simd-everywhere/simde/issues/13#issuecomment-1073005395_

**Comment by kapsyst** [comment] 2022-03-19 21:55
Thanks for reposting @mr-c.

Unfortunately this doesn't seem to be specific to SIMDe. I tried with regular SSE and get a similar error:

```
argument to '__builtin_ia32_shufps' must be a constant integer
```

See: https://stackoverflow.com/questions/38219436/neon-intrinsic-compile-error-argument-must-be-a-constant-when-using-vshr-n-u3. Applies to Neon but assuming the SSE error is for the same reason.

So you can probably close this issue.

**Comment by nemequ** [comment] 2022-03-20 18:19
Yeah, the problem is that a lot of the builtins which compile to instructions with immediate-mode parameters (basically, the value is encoded as part of the instruction instead of passed in a register) have to be integer constant expressions.  It's not even enough that the compiler knows the constant at compile time (i.e., constant by the `__builtin_constant_p` definition), they actually have to be integer constant expressions :(

We do sort of have a way around this in SIMDe; see the `SIMDE_CONSTIFY_*_` macros in [simde/simde-constify.h](https://github.com/simd-everywhere/simde/blob/master/simde/simde-constify.h).  Basically they expand to a big switch which handles each value with a different call.  If the value(s) are known at compile time the compiler should elide the unused cases, but you might still want to verify that the compiled code isn't too bad (and obviously make sure you compile with optimization enabled).

Other than that, your best option is probably to use something which doesn't require an immediate-mode parameter. For example, use `_mm_shuffle_epi8` instead of `_mm_shuffle_ps` or `_mm_shuffle_epi32`.

Pretty much all compilers have the same restriction.  I guess the thinking is that validity of the code shouldn't be determined by compiler optimization level, which seems reasonable, but it sure can be frustrating when you know the value is known at compile time... :(

**Closed by nemequ** 2022-03-20 18:19 UTC

**Comment by kapsyst** [comment] 2022-03-22 00:59
Hi @nemequ thank you for the detailed reply.

> We do sort of have a way around this in SIMDe; see the SIMDE_CONSTIFY_*_ macros in [simde/simde-constify.h](https://github.com/simd-everywhere/simde/blob/master/simde/simde-constify.h). Basically they expand to a big switch which handles each value with a different call. If the value(s) are known at compile time the compiler should elide the unused cases, but you might still want to verify that the compiled code isn't too bad (and obviously make sure you compile with optimization enabled).

Good to know that SIMDE_CONSTIFY_ exists. I ended up rearranging my intrinsics to loop through four m128s at a time, using fixed indices, and was able to get a speed win too. Makes sense now that you mention the value is encoded as part of the instruction.

Thanks for your help.
